services:
  db:
    image: postgres:16-alpine
    container_name: zuzdog-db
    environment:
      POSTGRES_DB: zuzdog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - zuzdog_pg_data:/var/lib/postgresql/data
      - ./backend/zuzdog-backend/src/main/resources/db/schemas/init-postgresql.sql:/docker-entrypoint-initdb.d/1-init-postgresql.sql
      - ./backend/zuzdog-backend/src/main/resources/db/schemas/mock-data.sql:/docker-entrypoint-initdb.d/2-mock-data.sql

  message-broker:
    image: apache/activemq-classic:5.18.3
    container_name: zuzdog-mq
    ports:
      - '61616:61616'
      - '8161:8161'

volumes:
  zuzdog_pg_data:
